#include <chrono>
#include <cstdlib>
#include <iostream>
#include <iterator>
#include <random>
#include <set>
#include <thread>
#include <utility>
#include <vector>

// Include necessary header files for non-blocking input handling
#ifdef _WIN32
    #include <conio.h>
#else
    #include <termios.h>
    #include <sys/select.h>
    #include <unistd.h>
#endif

// Non-blocking input handler: khbit() and setNonBlockingMode().
// Generated by Gemini AI (Gemini Flash Model)
bool kbhit() {
#ifdef _WIN32
    return _kbhit(); // Fungsi bawaan Windows dari <conio.h>
#else
    struct timeval tv = {0, 0};
    fd_set fds;
    FD_ZERO(&fds);
    FD_SET(STDIN_FILENO, &fds);
    return select(STDIN_FILENO + 1, &fds, NULL, NULL, &tv) > 0;
#endif
}

char readChar() {
#ifdef _WIN32
    return _getch(); // Ambil karakter langsung tanpa tunggu Enter & tanpa echo
#else
    char c;
    read(STDIN_FILENO, &c, 1);
    return c;
#endif
}

#ifndef _WIN32
void setNonBlockingMode(bool enable) {
    static struct termios oldt, newt;
    if (enable) {
        tcgetattr(STDIN_FILENO, &oldt);
        newt = oldt;
        // Matikan ICANON (line buffering) dan ECHO (tampilan karakter)
        newt.c_lflag &= ~(ICANON | ECHO);
        tcsetattr(STDIN_FILENO, TCSANOW, &newt);
    } else {
        // Kembalikan ke pengaturan semula
        tcsetattr(STDIN_FILENO, TCSANOW, &oldt);
    }
}
#endif

void clearScreen() {
    std::cout << "\033[2J\033[1;1H";
}

void sleepFor(int duration) {
    std::this_thread::sleep_for(std::chrono::milliseconds(duration));
}

enum class Direction {
    North,
    East,
    South,
    West
};

enum class GameStatus {
    Running,
    Stopped,
};

int dx[] = {-1, 0, 1, 0};
int dy[] = {0, 1, 0, -1};

using Cell = std::pair<int, int>;

const int SPACE_DEFAULT_HEIGHT = 13;
const int SPACE_DEFAULT_WIDTH = 26;
const char SPACE_DEFAULT_BG = '.';

const Cell SNAKE_DEFAULT_HEAD_POSITION = {0, 4};
const Direction SNAKE_DEFAULT_DIRECTION = Direction::East;
const int SNAKE_DEFAULT_LENGTH = 4;
const char SNAKE_DEFAULT_HEAD_SKIN = '@';
const char SNAKE_DEFAULT_BODY_SKIN = '#';

const Cell APPLE_DEFAULT_POSITION = {SPACE_DEFAULT_HEIGHT - 1, SPACE_DEFAULT_WIDTH - 1};
const char APPLE_DEFAULT_TEXTURE = '%';

const int GAME_DEFAULT_TARGET_FPS = 8;

class Space {
private:
    int height;
    int width;
    char background;
    std::vector<std::vector<char>> grid;

public:
    Space() : height(SPACE_DEFAULT_HEIGHT), width(SPACE_DEFAULT_WIDTH), background(SPACE_DEFAULT_BG), 
        grid(height, std::vector<char>(width, background)) {}

    void setPixelAtCell(Cell position, char texture) {
        auto [x, y] = position;
        if(x >= 0 && x < height && y >= 0 && y < width) {
            grid[x][y] = texture;
        }
    }

    int getHeight() {
        return height;
    }

    int getWidth() {
        return width;
    }

    void print() {
        for(int i = 0; i < height; i++) {
            for(int j = 0; j < width; j++) {
                std::cout << grid[i][j];
            }
            std::cout << '\n';
        }
    }

    void clear() {
        for(int i = 0; i < height; i++) {
            for(int j = 0; j < width; j++) {
                grid[i][j] = background;
            }
        }
    }
};

class Snake {
private:
    Cell head;
    std::vector<Cell> body;
    Direction currentDirection;
    int length;
    char headSkin;
    char bodySkin;
    bool isAlive = true;

public:
    Snake() {
        head = SNAKE_DEFAULT_HEAD_POSITION;
        length = SNAKE_DEFAULT_LENGTH;
        headSkin = SNAKE_DEFAULT_HEAD_SKIN;
        bodySkin = SNAKE_DEFAULT_BODY_SKIN;
        currentDirection = SNAKE_DEFAULT_DIRECTION;

        body.reserve(length - 1);
        Cell prevPosition = head;
        for(int i = 0; i < length - 1; i++) {
            body.push_back({
                prevPosition.first + dx[(static_cast<int>(currentDirection) + 2) % 4],
                prevPosition.second + dy[(static_cast<int>(currentDirection) + 2) % 4],
            });
            prevPosition = body[i];
        }
    }

    Cell getHeadPosition() {
        return head;
    }

    std::vector<Cell> getBodyPosition() {
        return body;
    }

    char getHeadSkin() {
        return headSkin;
    }

    char getBodySkin() {
        return bodySkin;
    }

    bool getSnakeStatus() {
        return isAlive;
    }

    void changeDirection(Direction newDirection) {
        int newDirectionInt = static_cast<int>(newDirection);
        int currentDirectionInt = static_cast<int>(currentDirection);

        if(abs(newDirectionInt - currentDirectionInt) != 2) {
            currentDirection = newDirection;
        }
    }

    void move(int spaceHeight, int spaceWidth, std::set<Cell> &unusedCell) {
        Cell newHead = {
            (head.first + dx[static_cast<int>(currentDirection)]) % spaceHeight,
            (head.second + dy[static_cast<int>(currentDirection)]) % spaceWidth,
        };

        for(auto cell : body) {
            if(cell == newHead) {
                isAlive = false;
                return;
            }
        }

        unusedCell.insert(body.back());

        for(int i = length - 2; i > 0; i--) {
            body[i] = body[i - 1];
        }

        body[0] = head;

        if(newHead.first < 0) newHead.first += spaceHeight;

        if(newHead.second < 0) newHead.second += spaceWidth;

        head = newHead;
        unusedCell.erase(head);
    }

    Cell eat() {
        int deltaX = body[length - 3].first - body[length - 2].first;
        int deltaY = body[length - 3].second - body[length - 2].second;

        Cell newCell = {
            body[length - 2].first - deltaX,
            body[length - 2].second - deltaY,
        };

        length++;
        body.reserve(length);
        body.push_back(newCell);

        return newCell;
    }
};

class Apple {
private:
    Cell position;
    char texture;

public:
    Apple() : position(APPLE_DEFAULT_POSITION), texture(APPLE_DEFAULT_TEXTURE) {}

    Cell getPosition() {
        return position;
    }

    void setPosition(Cell pos) {
        position = pos;
    }

    char getTexture() {
        return texture;
    }
};

class Game {
private:
    Space gameSpace;
    Snake snake;
    Apple apple;
    GameStatus status;
    std::set<Cell> unusedCell;
    int targetFps;
    int frameTime; // in millisecond
    int score = 0;

    void render() {
        gameSpace.setPixelAtCell(snake.getHeadPosition(), snake.getHeadSkin());
        
        for(auto cell : snake.getBodyPosition()) {
            gameSpace.setPixelAtCell(cell, snake.getBodySkin());
        }

        gameSpace.setPixelAtCell(apple.getPosition(), apple.getTexture());
    }

    void print() {
        clearScreen();
        gameSpace.print();
        gameSpace.clear();
    }

    void checkSnakeEatApple() {
        if(snake.getHeadPosition() == apple.getPosition()) {
            Cell newCell = snake.eat();
            score += 100;
            unusedCell.erase(newCell);
            generateRandomApple();
        }
    }

    void generateRandomApple() {
        int numUnusedCell = unusedCell.size();

        std::random_device rd;
        std::mt19937 gen(rd());
        std::uniform_int_distribution<> dist(0, numUnusedCell - 1);

        int cellIdx = dist(gen);

        Cell applePosition = *std::next(unusedCell.begin(), cellIdx);

        apple.setPosition(applePosition);
    }

    void gameLoop() {
        while(status == GameStatus::Running && snake.getSnakeStatus()) {
            if(kbhit()) {
                char c = readChar();

                if(c == 'q') status = GameStatus::Stopped;
                else if(c == 'w') snake.changeDirection(Direction::North);
                else if(c == 'd') snake.changeDirection(Direction::East);
                else if(c == 's') snake.changeDirection(Direction::South);
                else if(c == 'a') snake.changeDirection(Direction::West);
            }

            snake.move(gameSpace.getHeight(), gameSpace.getWidth(), unusedCell);

            checkSnakeEatApple();

            render();
            print();

            std::cout << "Your score is : " << score << '\n';
            
            sleepFor(frameTime);
        }
    }

public:
    Game() {
        status = GameStatus::Stopped;
        targetFps = GAME_DEFAULT_TARGET_FPS;
        frameTime = 1000 / targetFps;

        for(int i = 0; i < gameSpace.getHeight(); i++) {
            for(int j = 0; j < gameSpace.getWidth(); j++) {
                unusedCell.insert({i, j});
            }
        }

        unusedCell.erase(snake.getHeadPosition());

        for(auto cell : snake.getBodyPosition()) {
            unusedCell.erase(cell);
        }
    }

    int run() {
#ifndef _WIN32
        setNonBlockingMode(true);
#endif

        status = GameStatus::Running;

        gameLoop();

#ifndef _WIN32
        setNonBlockingMode(false);
#endif

        return score;
    }
};

void splashScreen() {
    std::cout << '\n';

    std::cout <<
                 "  ███████╗███╗   ██╗ █████╗ ██╗  ██╗███████╗\n"
                 "  ██╔════╝████╗  ██║██╔══██╗██║ ██╔╝██╔════╝\n"
                 "  ███████╗██╔██╗ ██║███████║█████╔╝ █████╗  \n"
                 "  ╚════██║██║╚██╗██║██╔══██║██╔═██╗ ██╔══╝  \n"
                 "  ███████║██║ ╚████║██║  ██║██║  ██╗███████╗\n"
                 "  ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝\n\n";

    std::cout << "                    v0.1.0                  \n\n";
    std::cout << "      A Terminal-based Classic Snake Game   \n";

    sleepFor(2000);

    clearScreen();
}

void welcome() {
    std::cout << "Snake++\n\n";

    std::cout << "A Terminal-based Classic Snake Game\n";
    std::cout << "v0.1.0\n\n";

    std::cout << "Made with love by Andhika Rahman\n\n";
}

void menu() {
    std::cout << "[P] Play\n";
    std::cout << "[S] Setting\n";
    std::cout << "[A] About\n";
    std::cout << "[Q] Quit\n";
}

void snakepp() {
    clearScreen();

    splashScreen();

    welcome();

    menu();
}

int main() {
    snakepp();

    return 0;
}
